development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:bc505fc041ae8dd734c3b5b78e3832e9@sole.redistogo.com:10279/
  channel_prefix: rails-boilerplate_production

# production:
#   adapter: redis
#   url: redis://redistogo:bc505fc041ae8dd734c3b5b78e3832e9@sole.redistogo.com:10279/
#   channel_prefix: rails_boilerplate_production


